plugins:
  - rubocop-rspec

inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"

Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 200
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "*.gemspec"
Style/Documentation:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3
RSpec/ExampleLength:
  Max: 10
RSpec/MultipleMemoizedHelpers:
  Max: 10
